FROM python:3.11-slim

WORKDIR /app
COPY . .

# Install system dependencies needed for psycopg2
RUN apt-get update && apt-get install -y gcc python3-dev libpq-dev

# Install Python dependenciesummmmmuRUN pip install fastapi uvicorn sqlalchemy psycopg2-binary

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
